### ISSUE TITLE
more urls

### ISSUE THREAD

**Issue by pmetemp** [Ruddernation-Designs/Adobe-URL-Block-List#1]
127.0.0.1 cc-api-data.adobe.io 
127.0.0.1 ic.adobe.io 
127.0.0.1 genuine.adobe.com 
127.0.0.1 prod.adobegenuine.com 
127.0.0.1 assets.adobedtm.com

**Comment by Ruddernation-Designs** [comment]
Thank you, 
I'll add them now.
