### ISSUE TITLE
does this prevent Premiere Pro from recongizing AE?

### ISSUE THREAD

**Issue by hisprofile** [Ruddernation-Designs/Adobe-URL-Block-List#14]
sorry, just going to treat this like a comment section. are these hosts entries the reason the two apps cannot communicate with each other, or did i install something i wasn't meant to?

**Comment by Ruddernation-Designs** [comment]
@hisprofile That's okay, 
If it's stopped communicating then you could try removing the IP's and try again,
it might be a single IP/Host blocking it.
