### ISSUE TITLE
`assets.adobedtm.com` breaks some websites

### ISSUE THREAD

**Issue by MitchTalmadge** [Ruddernation-Designs/Adobe-URL-Block-List#18]
Visiting dyson.com, I found the page to be loading for a very long time. I opened DevTools and found that they are using some kind of tracker from Adobe, at `assets.adobetm.com`. When commenting out the following Hosts rule, the website resumed loading quickly:

`127.0.0.1 assets.adobedtm.com`

I am curious if we are certain that we need this rule? I find it unlikely that Adobe would check for license usage on an assets domain, but I am certainly not an expert in this area and could be wrong.

I don't support trackers, but I also would take a tracked and quick web browsing experience than untracked and un-usably slow.

Thanks!

**Comment by MitchTalmadge** [comment]
Update, I just tried out the `hosts-beta` file and it is working great. My programs are not having popups and my web browsing is fast. :)

**Comment by Ruddernation-Designs** [comment]
> Update, I just tried out the `hosts-beta` file and it is working great. My programs are not having popups and my web browsing is fast. :)

Glad its working, sorry for the delayed reply, but glad it all worked out
