### ISSUE TITLE
Even with current the HOST file entries, I got license "time-bombs."

### ISSUE THREAD

**Issue by TheRealDjElite** [Ruddernation-Designs/Adobe-URL-Block-List#2]
Anyone else?

**Comment by Ruddernation-Designs** [comment]
Do you have a way of checking the out going IP's?

**Comment by Ruddernation-Designs** [comment]
Were you able to check the IPs or URL's going out on your PC?
Also, block any Adobe product using the firewall.

**Comment by TheRealDjElite** [comment]
I was going to create firewall rules for the .EXE  but instead updated to v3-m0nkrus and everything seems to be all good.

**Comment by messi89** [comment]
you can't block ip address from hosts file...

You need to lookup for the reverse dns instead

**Comment by MousaAlribi** [comment]
Add this 127.0.0.1 4vzokhpsbs.adobe.io

**Comment by McCarthee** [comment]
> Add this 127.0.0.1 4vzokhpsbs.adobe.io

Seems Adobe have changed it again, any ideas?

**Comment by messi89** [comment]
> > Add this 127.0.0.1 4vzokhpsbs.adobe.io
> 
> Seems Adobe have changed it again, any ideas?

block adobe sotfwares with windows firewall it's better

**Comment by MousaAlribi** [comment]
> > Add this 127.0.0.1 4vzokhpsbs.adobe.io
> 
> Seems Adobe have changed it again, any ideas?

try this 127.0.0.1 69tu0xswvq.adobe.io

you can also follow this thread for more updates 
https://www.reddit.com/r/AdobeZii/comments/z67rpm/potential_fix_for_adobe_genuine_software_popup_on/

@messi89 I have tried firewall before but sadly it doesn't work! I wish there is an easier way

**Comment by Ruddernation-Designs** [comment]
I've added that now, so give it a try now.

**Comment by BuildBackBuehler** [comment]
Hey, 

This was the previous list I was using before. I mashed it together with yours, no clue what overlap does/doesn't exist, but in case it is helpful!

https://wtools.io/paste-code/bHIR

**Comment by Ruddernation-Designs** [comment]
@BuildBackBuehler Thank you very much, I'll check it and add it later.

**Comment by MorganBlack** [comment]
0.0.0.0 7m31guub0q.adobe.io

and

https://rentry.co/psnfoandhostblock#i-just-want-the-new-ip-to-block

**Comment by 000ev** [comment]
new line needed 5-5-24
