### ISSUE TITLE
Its Showing C:\Windows\System32\drivers\etc\hosts.txt You don't have permission to save in this location. Contact the administrator to obtain permission. Would you like to save in the Documents folder instead?

### ISSUE THREAD

**Issue by ZubairSadaqat** [Ruddernation-Designs/Adobe-URL-Block-List#21]
its showing this message 
C:\Windows\System32\drivers\etc\hosts.txt
You don't have permission to save in this location.
Contact the administrator to obtain permission.
Would you like to save in the Documents folder instead?
![image](https://github.com/user-attachments/assets/81a04cc7-2b63-4e2d-9b7b-f1dcf121627f)

**Comment by kmbhaug** [comment]
When you open your text editor like Notepad, make sure to open it as Administrator. Also, after you save the file, remove the .txt from the file name

**Comment by pokameni** [comment]
You can also use PowerToys Hosts Editor tool.
