### ISSUE TITLE
This list work but i cant login to Behance

### ISSUE THREAD

**Issue by genchan** [Ruddernation-Designs/Adobe-URL-Block-List#5]
This list work for me. but because this list now i cant login to Behance, i can still view some of content, but to view full content i need to login. I know it cause by this list because i delete all list on host file, now i can easily login. is there anyway to ignore host file while browsing? or adding something on the list so i can login to behance? i am using chrome.

**Comment by Ruddernation-Designs** [comment]
Hi @genchan,
Do you by any chance know the IP address Behance is trying to connect to?
If you remove the code from the HOST file, bit by bit and test each time until Behance connects and then let me know which addresses you removed and I'll update accordingly.
